#!/system/bin/sh

# Permission script

mkdir /data/adt
chmod 777 /data/adt
mkdir /data/edt/logs
chmod 777 /data/edt/logs

logFile=/data/edt/logs/S30edt_perms.log
if [ -f $logFile ]; then
	rm $logFile
fi
touch $logFile
chmod 777 $logFile

sysrw
echo "Setting permissions" >> $logFile
		chmod 0771 /data/app/
		
		# standard permissions
        for file in /system/app/* /system/framework/* /data/app/*; do
                echo "    setting permissions (644) for $file" >> $logFile
                chmod 0644 $file
        done
		
		# su
		chmod 06755 /system/bin/su
		chmod 06755 /system/xbin/su
		
        
        echo "chmodding init.d folder"
        chmod 0777 /system/etc/init.d
        
		chmod 0755 /system/etc/init.d
        for file in /system/etc/init.d/*; do
                echo "    setting permissions (777) for $file" >> $logFile
                chmod 0755 $file
        done
echo "Permissions set" >> $logFile
sysro
